gsi:
  esSigKeyConfig:
    fileName: classpath:cert/ref-es-sig.p12
    keyId: puk_idp_sig
    use: sig
  tokenSigKeyConfig:
    fileName: classpath:cert/ref-es-sig.p12
    keyId: puk_fed_idp_token
    use: sig
  serverUrl: "${GSI_SERVER_URL:https://gsi.dev.gematik.solutions}"
  fedmasterUrl: "${FEDMASTER_SERVER_URL:https://app-test.federationmaster.de}"
  debug:
    requestLogging: true
  loglevel: info
server:
  port: ${SERVER_PORT:8085}
management:
  server:
    port: ${MANAGEMENT_PORT:8185}
  endpoints:
    web:
      exposure:
        include: "health"
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
    logfile:
      enabled: true
