gsi:
  esSigPrivKeyConfig:
    fileName: keys/ref-gsi-sig-privkey.pem
    keyId: puk_idp_sig
    use: sig
    addX5c: false
  esSigPubKeyConfig:
    fileName: keys/ref-gsi-sig-pubkey.pem
    keyId: puk_idp_sig
    use: sig
  tokenSigPrivKeyConfig:
    fileName: keys/ref-gsi-sig-privkey.pem
    keyId: puk_fed_idp_token
    use: sig
    addX5c: false
  tokenSigPubKeyConfig:
    fileName: keys/ref-gsi-sig-pubkey.pem
    keyId: puk_fed_idp_token
    use: sig
  serverUrl: "${GSI_SERVER_URL:http://127.0.0.1:8085}"
  fedmasterUrl: "${FEDMASTER_SERVER_URL:http://127.0.0.1:8083}"
  fedmasterSigPubKeyFilePath: "keys/ref-fedmaster-sig-pubkey.pem"
  debug:
    requestLogging: true
  loglevel: debug
server:
  port: ${SERVER_PORT:8085}
management:
  server:
    port: ${MANAGEMENT_PORT:8185}
  endpoints:
    web:
      exposure:
        include: "health"
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
    logfile:
      enabled: true
