gsi:
  sigKeyConfig:
    fileName: classpath:cert/ref-es-sig.p12
    keyId: puk_fed_idp_sig
    use: sig
  serverUrl: "${GSI_SERVER_URL:http://localhost:8085}"
  fedmasterUrl: "${FEDMASTER_SERVER_URL:http://hidden}"
server:
  port: ${SERVER_PORT:8085}
management:
  server:
    port: ${MANAGEMENT_PORT:8185}
  endpoints:
    web:
      exposure:
        include: "health"
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
    logfile:
      enabled: true
