fedmaster:
  fedmasterSigPrivKeyConfig:
    fileName: keys/ref-fedmaster-sig-privkey.pem
    keyId: puk_fed_sig
    use: sig
    addX5c: false
  fedmasterSigPubKeyConfig:
    fileName: keys/ref-fedmaster-sig-pubkey.pem
    keyId: puk_fed_sig
    use: sig
    addX5c: false
  relyingPartyConfigs:
    - issuer: "http://gras.local:8084"
      organization-name: "GRAS"
      keyConfig:
        fileName: "keys/ref-gras-pubkey.pem"
        keyId: "puk_fd_sig"
        use: "sig"
        x5cInJwks: false
  identityProviderConfigs:
    - issuer: "http://gsi.local:8085"
      organization-name: "GSI"
      keyConfig:
        fileName: "keys/ref-gsi-es-sig-pubkey.pem"
        keyId: "puk_idp_sig"
        use: "sig"
        x5cInJwks: false
  serverUrl: "${FEDMASTER_SERVER_URL:http://fedmaster.local:8083}"
  debug:
    requestLogging: true
  loglevel: debug
server:
  port: ${SERVER_PORT:8083}
management:
  server:
    port: ${MANAGEMENT_PORT:8183}
  endpoints:
    web:
      exposure:
        include: "health"
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
    logfile:
      enabled: true
