fedmaster:
  fedmasterSigPrivKeyConfig:
    fileName: keys/ref-fedmaster-sig-privkey.pem
    keyId: puk_fed_sig
    use: sig
    addX5c: false
  fedmasterSigPubKeyConfig:
    fileName: keys/ref-fedmaster-sig-pubkey.pem
    keyId: puk_fed_sig
    use: sig
    addX5c: false
  relyingPartyConfigs:
    - issuer: "${ISSUER_RP_01:http://127.0.0.1:8084}"
      organization-name: "GRAS"
      keyConfig:
        fileName: "keys/ref-gras-pubkey.pem"
        keyId: "puk_fd_sig"
        use: "sig"
        x5cInJwks: false
  identityProviderConfigs:
    - issuer: "${ISSUER_IDP_01:http://127.0.0.1:8085}"
      organization-name: "GSI"
      keyConfig:
        fileName: "keys/ref-gsi-es-sig-pubkey.pem"
        keyId: "puk_idp_sig"
        use: "sig"
        x5cInJwks: false
  serverUrl: "${FEDMASTER_SERVER_URL:http://127.0.0.1:8083}"
server:
  port: ${SERVER_PORT:8083}
management:
  server:
    port: ${MANAGEMENT_PORT:8183}
  endpoints:
    web:
      exposure:
        include: "health"
    access:
      max-permitted: read-only
      default: read_only
  endpoint:
    health:
      access: read_only
      probes:
        access: read-only
    metrics:
      access: read_only
    logfile:
      access: read_only
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
logging:
  level:
    de.gematik: ${LOG_LEVEL_GEMATIK:debug}
  CommonsRequestLoggingEnabled: ${REQUEST_LOGGING_ENABLED:true}
