on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest-16-cores

    steps:
      - name: Install dependencies
        run: apt-get install maven

